### ISSUE TITLE
paper title

### ISSUE THREAD

**Issue by lichajuan** [sharnett/power-grid-attack#1]
What is the thesis title of this project?

**Comment by sharnett** [comment]
Adding to the README now

**Comment by lichajuan** [comment]
&nbsp; Thanks, I find it.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sharnett/power-grid-attack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 凌晨1:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sharnett/power-grid-attack] paper title (Issue #1)





 
Adding to the README now
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
